apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/webapp/templates/deployment.yaml
- manifests/webapp/templates/service.yaml

labels:
- includeSelectors: true
  pairs:
    managed-by: kustomize
