apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: webapp-prod

namePrefix: prod-


patches:
- path: patches/deployment-resources.yaml
  target:
    kind: Deployment
    name: webapp
labels:
- includeSelectors: true
  pairs:
    environment: production
    managed-by: kustomize
