resources:
- ../../base
- configmap.yaml

namePrefix: prod-


patches:
- path: replica-patch.yaml
  target:
    kind: Deployment
    name: nginx
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    env: prod

images:
  - name: nginx
    newTag: "1.24.0"
