apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
    environment: production
    managed-by: kustomize
  name: prod-webapp-service
  namespace: webapp-prod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
    environment: production
    managed-by: kustomize
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
    environment: production
    managed-by: kustomize
    version: v1
  name: prod-webapp
  namespace: webapp-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      environment: production
      managed-by: kustomize
  template:
    metadata:
      labels:
        app: webapp
        environment: production
        managed-by: kustomize
        version: v1
    spec:
      containers:
      - image: nginx:1.21
        imagePullPolicy: IfNotPresent
        name: webapp
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
